// the createSquareDivs code below was generated by ChatGPT
// ---------------------------------------------------------
const container = document.getElementById('container');

function createSquareDivs(num) {
  for (let i = 0; i < num; i++) {
    const square = document.createElement('div');
    square.classList.add('square');
    container.appendChild(square);
  }
}

const numberOfSquares = 1130;
createSquareDivs(numberOfSquares);

// ------------------------------------------

let colors = ["#ff0000", "#ff6200", "#fff700", "#00ff62", "#00d0ff", "#0040ff", "#5500ff", "#ff0090", "#ffffff", "#000000"];
let randomColor = Math.floor(Math.random() * colors.length);

let squares = document.querySelectorAll(".square");
for (let box of squares) {
    box.style.backgroundColor = colors[randomColor];
    box.style.opacity = Math.random();
    if (box.style.backgroundColor = )
}

let randombg = Math.floor(Math.random() * colors.length);
document.body.style.backgroundColor = colors[randombg];


// Below code is from w3 schools
function reload() {
  window.location.reload();
}

setTimeout(reload, 5000);